### PR TITLE
Throw exceptions in Misc.getSha1

### LINKED ISSUE #397: Should Misc.getSha1 throw an exception instead of returning an empty byte array?
Currently `Misc. getSha1` returns `null` when it could not calculate the sha1 for a stream, however findbugs regards this as a problem as a result it has been replaced with an empty byte array in pr #393. Some more thought should be put in to wether or not it should throw an exception and if so what exception should be thrown.

### PR DESCRIPTION
**Pull request by tomblench**
Fixes #397

### CODE REVIEW

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java [hunk 1]
```diff
@@ -51,11 +53,10 @@ public static boolean isRunningOnAndroid() {
             while ((bytesRead = shaFis.read(buf)) != -1) {
                 sha1.update(buf, 0, bytesRead);
             }
-        } catch (RuntimeException e){
+        } catch (NoSuchAlgorithmException e){
+            throw new IllegalStateException(e);
+        } catch (IOException e) {
```
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: Remove the catch block for IOException.
