### PR TITLE
Throw DocumentStoreException when revsDiff fails.

### LINKED ISSUE #444: DatabaseImpl#revsDiff returns null on error
DatabaseImpl#revsDiff returns null on error, this should throw a checked exception.

### PR DESCRIPTION
**Pull request by rhyshort**
Throw DocumentStoreException when revsDiff queue task throws an ExecutionException.

Fixes #444

### CODE REVIEW

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/documentstore/DatabaseImplRevsDiffTest.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
 public class DatabaseImplRevsDiffTest extends BasicDatastoreTestBase{
 
     @Test
-    public void revsDiff_emptyInput_returnEmpty() {
+    public void revsDiff_emptyInput_returnEmpty() throws Exception {
```
Comment (emlaver) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/documentstore/DatabaseImplRevsDiffTest.java]: Does this need to be `Exception` or can `DocumentStoreException` meet the requirement?

Comment (rhyshort) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/documentstore/DatabaseImplRevsDiffTest.java]: It could be `DocumentStoreException` but with it only being test code I didn't think it mattered too much.

Comment (emlaver) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/documentstore/DatabaseImplRevsDiffTest.java]: Ok, that's true, up to you then if you want to change it.
