### PR TITLE
QueryResultIterator NoSuchElementException

### LINKED ISSUE #318: QueryResultIterator doesn't account for Post SQL matching
`QueryResultIterator` doesn't count for post sql query matching, resulting in a `NoSuchElementException` being thrown when we attempt to provide a document to `next()` call via the list iterator. This occurs when a batch is emptied by the Post SQL matcher.

### PR DESCRIPTION
**Pull request by rhyshort**
## What
Correctly calculate if there are more documents to be iterated over.

## How.

Calculate if there a remaing documents to iterator over correctly, by loading
the next batch of documents before returning the last document of the previous
batch, and only if the limit on the number of results hasn't been reached.

## Tests

New tests added to `QueryWithoutCoveringIndexesTest` which populate the datastore with documents which match using the part of the query which can be performed in SQL, but doesn't match the remaining parts of the query using post hoc matcher. 

## Issues

Fixes #318

### CODE REVIEW

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java [hunk 1]
```diff
@@ -122,10 +122,16 @@ public DocumentRevision next() {
             if (!this.hasNext()) {
                 throw new NoSuchElementException();
             }
-            if (!documentBlock.hasNext()) {
+
+            DocumentRevision doc =  documentBlock.next();
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: I think this could do with a comment explaining why it is safe to call this without an explicit proceeding `documentBlock.hasNext()` just so it is easier for the next person who wanders into this block.

`this.hasNext()` calls `documentBlock.hasNext()`, but it ORs that result with another check so it is at first glance possible to reach this line without a document being available in the `documentBlock`. I think it would be helpful to clarify that in the case of the initial or final block being empty the range check in `hasNext` protects this call.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java [hunk 2]
```diff
@@ -122,10 +122,16 @@ public DocumentRevision next() {
...
+
+            // Only load the next batch if the limit hasn't been reached, if it has
+            // it will cause an off by on error, eg instead of 60, you'd get 61 results.
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: off by on**e**

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java (hunk 1 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: thoughts @ricellis 
```java
            // it is always safe to call documentBlock.next() without calling hasNext because
            // the this.hasNext() will return false if there are no more documents to read this
            // is because we load the next block of documents (if there are any), before
            // returning the last document from the last batch, ensuring that documentBlock.next()
            // will always have a document to return.
            DocumentRevision doc =  documentBlock.next();

```

Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: I wonder if there is a record for comment per line :)
I think that is helpful though.

Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: Cool, Guinness world records will know if there is one.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java (hunk 2 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: fixed in a5f0033

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java (hunk 1 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/QueryResult.java]: added in a5f0033

**Comment by ricellis** [comment]
+1 but I'd like another reviewer to check this too as the iteration has subtleties and I think another thought pattern (further removed from the original debugging) would be good.

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java [hunk 3]
```diff
@@ -109,6 +111,72 @@ public void canQueryWithoutIndexSingleClause() throws Exception {
...
+            Map<String, Object> bodyMap = new HashMap<String, Object>();
+            bodyMap.put("name", "rhys");
+            bodyMap.put("age", 12);
+            bodyMap.put("pet", "cat");
+            bodyMap.put("town", "cardiff");
+            rev.setBody(DocumentBodyFactory.create(bodyMap));
+            ds.createDocumentFromRevision(rev);
+        }
+
+
```
Comment (brynh) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java]: I'd prefer only one blank line here.

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java [hunk 4]
```diff
@@ -109,6 +111,72 @@ public void canQueryWithoutIndexSingleClause() throws Exception {
...
+            } else {
+                bodyMap.put("town", "bristol"); //+2
+            }
+            rev.setBody(DocumentBodyFactory.create(bodyMap));
+            ds.createDocumentFromRevision(rev);
+        }
+
+
+
+
```
Comment (brynh) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java]: I'd prefer only one blank line here.

**Comment by brynh** [comment]
+1 once extra blank lines are removed.

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java (hunk 3 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java]: done in 494aaf3

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java (hunk 4 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/QueryWithoutCoveringIndexesTest.java]: done in 494aaf3
