### PR TITLE
Fix find bugs warnings

### LINKED ISSUE #388: Resolve outstanding findbugs issues
Fix the remaining issues reported by findbugs and enable the most sensitive level of reporting.

### PR DESCRIPTION
**Pull request by rhyshort**
Fix findbugs warnings and enable findbugs at low level.

Fixes #388

### CODE REVIEW

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java [hunk 1]
```diff
@@ -1260,4 +1224,52 @@ public DocumentRevision deleteDocumentFromRevision(final DocumentRevision rev) t
     }
 
 
+    private static class GetPublicIdentifierCallable implements SQLCallable<String> {
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java]: Callables go in their own files

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java [hunk 2]
```diff
@@ -928,7 +890,7 @@ public Void call(SQLDatabase db) throws Exception {
                             if (newWinnerTx.getClass().equals(DocumentRevision.class)) {
                                 // user gave us a new DocumentRevision instance
                                 isNewOrUpdatedRevision = true;
-                            } else if (newWinnerTx.getClass().equals(InternalDocumentRevision.class)) {
+                            } else if (newWinnerTx instanceof InternalDocumentRevision) {
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java]: is instanceof correct here? we need to distinguish between subtypes and supertypes and I thought that getClass() was the better check for this

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/replication/QueuingExecutorCompletionService.java [hunk 3]
```diff
@@ -14,6 +14,7 @@
 
 package com.cloudant.sync.internal.replication;
 
+import java.util.Observable;
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/replication/QueuingExecutorCompletionService.java]: I don't think this import is needed.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java [hunk 4]
```diff
@@ -108,8 +109,9 @@ private ExecuteResult(InputStream stream,
                 case 3:
                     // 3xx redirection
                     throw new CouchException("Unexpected redirection (3xx) code encountered", responseCode);
-                case 4:
+                case 4: case 5:
                     // 4xx errors normally mean we are not authenticated so we shouldn't retry
+                    // 5xx errors are transient server errors so we should retry
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: logic is broken here, case 5 previously had `needsCouchException = true`

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/InternalDocumentRevision.java [hunk 5]
```diff
@@ -204,7 +202,7 @@ public int getGeneration() {
 
     @Override
     public ChangeNotifyingMap<String, Attachment> getAttachments() {
-        return attachments;
+        return (ChangeNotifyingMap<String, Attachment>) attachments;
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/InternalDocumentRevision.java]: this cast looks ugly compared to using a more specific type on the field - what's the reason for it?

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java [hunk 6]
```diff
@@ -394,4 +389,10 @@ private static String generateIndexName(Set<String> existingIndexNames) throws E
         }
     }
 
+    private static class ListIndexesCallable implements SQLCallable<List<Index>> {
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java]: seems pretty pointless to have a callable for a 1 liner

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java [hunk 7]
```diff
@@ -390,4 +319,100 @@ public DBParameter(String tableName, ContentValues contentValues) {
         }
     }
 
+    private static class SequenceNumberForIndexCallable implements SQLCallable<Long> {
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java]: callables should (probably, if we're being consistent with past usage) go into their own files

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig [hunk 8]
```diff
@@ -0,0 +1,460 @@
+/*
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig]: you checked in a file generated by patch/diff

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java [hunk 9]
```diff
@@ -420,8 +419,7 @@ public void putAttachmentStream(String id, String rev, String attachmentName, St
             options.put("att_encoding_info", true);
         }
         options.put("open_revs", jsonHelper.toJson(revisions));
-        return this.getDocument(id, options, new TypeReference<List<OpenRevision>>() {
-        });
+        return this.getDocument(id, options,new CouchClientTypeReference<List<OpenRevision>>());
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: needs a space after `options,`
and
we can probably benefit from having some static fields representing the types we use most e.g. :
`static final TYPE_REF_LIST_OPEN_REVS = new CouchClientTypeReference<List<OpenRevision>>();`
and equivalently for `List<Response>`, `DocumentRevs`

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig [hunk 10]
```diff
@@ -0,0 +1,460 @@
...
+ * Copyright © 2014 Cloudant, Inc. All rights reserved.
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig]: This file is not a valid Java class any more, looks like bad merging.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java (hunk 6 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java]: It saves the overhead of having the reference to the enclosing class, not sure how much of a overhead it is, @ricellis could probably explain more.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java (hunk 7 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java]: Yes they should, but that would be part of the issue to host them into callables and consolidate where required / appropriate  .

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig (hunk 8 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java.orig]: Removed in 92d7377

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 4 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: Wouldn't the else block on 120 take care of that? Perhaps you mean that `fatal` should only be set to `true` if the response code isn't 5xx?

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java (hunk 2 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java]: I think so, unless we are worried that the ProjectDocumentRevision could come into here?

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java [hunk 11]
```diff
@@ -199,9 +199,6 @@ private void updateIndex(final String indexName,
                                                             initialArgs,
                                                             indexName,
                                                             rev);
-                if (parameter == null) {
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java]: I can see this and it's friend a few lines further on were removed because `com.cloudant.sync.internal.query.IndexUpdater#populateDBParameter` doesn't appear to be able to return null. However, I wonder if that method actually needs looking at because there is no `else` case for if we couldn't figure out the type and then not indexing that field.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 9 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: This changed slightly in a later commit, it now uses the `JavaType` class from Jackson, (`TypeReference`s don't work as static class, not sure why.) The rest is still valid, I'll add the fields as required.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/SavedAttachment.java [hunk 12]
```diff
@@ -66,7 +66,7 @@ public SavedAttachment(long seq, String name, byte[] key, String type, Encoding
 
         this.revpos = revpos;
         this.seq = seq;
-        this.key = Arrays.copyOf(key, key.length);
+        this.key = key == null? null : Arrays.copyOf(key, key.length);
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/SavedAttachment.java]: spacing incorrect around `?`

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DocumentRevisionBuilder.java [hunk 13]
```diff
@@ -28,26 +28,6 @@
  */
 public class DocumentRevisionBuilder {
 
-
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DocumentRevisionBuilder.java]: Was all this just obsolete? If not where did it go?

Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DocumentRevisionBuilder.java]: It was completely unused. I think it stems from a time before we allowed users to `new` up `DocumentRevisions`

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java [hunk 14]
```diff
@@ -112,8 +113,8 @@ public static void checkNotNull(Object param, String errorMessagePrefix) throws
      */
     public static void checkNotNullOrEmpty(String param, String errorMessagePrefix) throws
             IllegalArgumentException {
-        checkArgument(!isStringNullOrEmpty(param), (errorMessagePrefix != null ? errorMessagePrefix :
-                "Parameter") + " must not be " + param == null ? "null." : "empty.");
+        // Null is never passed as the parameter here, as per FindBugs and Intellij inspections.
```
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: Just double checked the usages, the front facing API uses this. First glance it was just the SQL code, so I removed the check, backing out and replacing with exclude.

Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: done in 62136e3

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/SavedAttachment.java (hunk 12 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/SavedAttachment.java]: fixed in 27b0d45

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java (hunk 6 above)
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexCreator.java]: Right it is a reduction in memory overhead. We can be pragamatic, if `IndexCreator` is a singleton then I think we're only ever going to have one copy of it and it's anonymous inner. I think the warning is more relevant for cases where we might generate hundreds of instances of inners each holding an unnecessary reference (in the case that they could be a replaced by a static class). Nonetheless we have a made a decision to extract callables so we should probably just be consistent.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java (hunk 11 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java]: That probably needs some investigation if that method is doing the "right thing" I think it used to add `null` to the content values if it couldn't figure it out, and then `null` values would be skipped later in the code iirc, @tomblench Does that sound familiar for the method `com.cloudant.sync.internal.query.IndexUpdater#populateDBParameter` ?

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 4 above)
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: I probably meant case 5 previously had `this.fatal = false`

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DocumentRevisionBuilder.java (hunk 13 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DocumentRevisionBuilder.java]: raised #396 to investigate the potential loss of function.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java (hunk 11 above)
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/query/IndexUpdater.java]: Correct, populateDBParameter would put a `null` into `contentValues` if the type wasn't one we understood (https://github.com/cloudant/sync-android/blob/master/cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/query/IndexUpdater.java#L330). And then that `null` would be skipped later, all entirely pointless.

However, that's for one `contentValues` entry on `DBParameter`.  These null checks are correct to be removed since `populateDBParameter` never returns null.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 4 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: fixed in 582d769

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 9 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: 546ab10

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java [hunk 15]
```diff
@@ -113,7 +113,8 @@ public static void checkNotNull(Object param, String errorMessagePrefix) throws
      */
     public static void checkNotNullOrEmpty(String param, String errorMessagePrefix) throws
             IllegalArgumentException {
-        // Null is never passed as the parameter here, as per FindBugs and Intellij inspections.
+        checkArgument(!isStringNullOrEmpty(param), (errorMessagePrefix != null ? errorMessagePrefix :
+              "Parameter") + " must not be " + param == null ? "null." : "empty.");
         checkArgument(!isStringNullOrEmpty(param), errorMessagePrefix + " must not be empty.");
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: You re-added the old line, but left the new code in place, now we might check twice.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/json/JSONHelper.java [hunk 16]
```diff
@@ -104,4 +107,17 @@ public JavaType mapStringToObject(){
         return this.getTypeFactory().constructParametricType(Map.class,String.class,Object.class);
     }
 
+    public JavaType mapStringMissingRevisions(){
+        return this.getTypeFactory().constructParametricType(Map.class, String.class, CouchClient
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/json/JSONHelper.java]: I still think we could make these static constants, but I'm happy for that to defer to some other time. In fact I think we could make this whole JSONHelper utility static instead of having loads of them.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java (hunk 2 above)
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/documentstore/DatabaseImpl.java]: Yes, this is ok unless we are concerned about sub-classes of `InternalDocumentRevision` that we should not cast or assume to be modified.

**Comment by ricellis** [comment]
Approved, but don't forget to remove that redundant line.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java (hunk 15 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: fixed in fbdae4e

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java [hunk 17]
```diff
@@ -108,9 +109,10 @@ private ExecuteResult(InputStream stream,
                 case 3:
                     // 3xx redirection
                     throw new CouchException("Unexpected redirection (3xx) code encountered", responseCode);
-                case 4:
+                case 4: case 5:
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: I still don't like the logic here. Breaking out 1xx,2xx,3xx,4xx,5xx is the most logical way to partition things because they are distinct ranges of error codes with different means. It doesn't make sense to effectively say "if 4 or 5" and then later say "oh but only if 5". I think it's more logical to have a case statement breaking them down to the hundreds and then refining within each hundred.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java [hunk 18]
```diff
@@ -89,7 +90,9 @@ private static boolean isFtsAvailable() {
     public static SQLDatabase openSQLDatabase(File dbFile, KeyProvider provider) throws IOException, SQLException {
         Misc.checkNotNull(dbFile, "dbFile");
         File dbDirectory = dbFile.getParentFile();
-        dbDirectory.mkdirs();
+        if (!dbDirectory.mkdirs()){
+            logger.info(String.format(Locale.ENGLISH, "Did not create directories for path: %s directories may already exist", dbFile));
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java]: Not sure if this deserves a logger.info. The more interesting case is probably when it does create the directory.

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java [hunk 19]
```diff
@@ -50,9 +51,11 @@ public static boolean isRunningOnAndroid() {
             while ((bytesRead = shaFis.read(buf)) != -1) {
                 sha1.update(buf, 0, bytesRead);
             }
+        } catch (RuntimeException e){
+            throw e;
         } catch (Exception e) {
             logger.log(Level.WARNING,"Problem calculating SHA1 for stream",e);
-            return null;
+            return new byte[]{};
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/util/Misc.java]: It's possible that throwing an exception is the more correct behaviour here

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/datastore/encryption/KeyUtilsTest.java [hunk 20]
```diff
@@ -42,19 +42,6 @@ public EncryptionKey getEncryptionKey() {
     }
 
     @Test
-    public void sqlCipherKeyForKeyProvider_nullKeyBytes() {
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/datastore/encryption/KeyUtilsTest.java]: Why was this removed?

File: cloudant-sync-datastore-javase/src/main/java/com/cloudant/sync/internal/sqlite/sqlite4java/SQLiteWrapperUtils.java [hunk 21]
```diff
@@ -84,7 +84,7 @@ public static SQLiteStatement bindArguments(SQLiteStatement stmt, Object[] bindA
             bindArgs = new Object[]{};
         }
 
-        final int count = bindArgs != null ? bindArgs.length : 0;
+        final int count =  bindArgs.length;
```
Comment (tomblench) [inline cloudant-sync-datastore-javase/src/main/java/com/cloudant/sync/internal/sqlite/sqlite4java/SQLiteWrapperUtils.java]: remove extra space

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/datastore/encryption/KeyUtilsTest.java (hunk 20 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/datastore/encryption/KeyUtilsTest.java]: Incorrect behaviour,  `EncryptionKey` cannot return null for keyBytes, the constructor ensures this, but the test deliberately bypasses the restriction imposed by the constructor.

File: cloudant-sync-datastore-javase/src/main/java/com/cloudant/sync/internal/sqlite/sqlite4java/SQLiteWrapperUtils.java (hunk 21 above)
Comment (rhyshort) [inline cloudant-sync-datastore-javase/src/main/java/com/cloudant/sync/internal/sqlite/sqlite4java/SQLiteWrapperUtils.java]: removed in 6861e95

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java (hunk 17 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/mazha/CouchClient.java]: backed out in fa092ba

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java (hunk 18 above)
Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java]: I'd rather have a log message for a failure case than the successful case since the next two checks should work just fine. The level can always be lowered to `FINE`, `FINER` or `FINEST`.

Comment (tomblench) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java]: Returning false isn't necessarily a failure case. It could mean that the directories were already there.

Comment (rhyshort) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/internal/sqlite/SQLDatabaseFactory.java]: yes, which the current log message takes account for.
