### PR TITLE
Correctly perform cookie authentication

### LINKED ISSUE #415: Android Sync Update (1.1.3) Causes Failed to get cookie from server error when using API key permissions
I have tested this from 1.1.2 (which works fine) and 1.1.3, which causes the following error when attempting to utilize api Key permissions:

```
E/CookieInterceptor: Failed to get cookie from server, response code {0}, cookie authentication will not be attempted again
Batch 0 ended with error:
CouchException: error: unauthorized, reason: _reader access is required for this request, statusCode: 401, msg: Unauthorized, cause: java.io.FileNotFoundException: https://f80a1a79-5d2f-4fe1-8ff3-f78abcad4fb1-bluemix.cloudant.com:443/ocimaoi/_bulk_get
                        at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:139)
                        at com.cloudant.mazha.CouchClient$ExecuteResult.<init>(CouchClient.java:89)
                        at com.cloudant.mazha.CouchClient.execute(CouchClient.java:193)
                        at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749)
                        at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280)
                        at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176)
                        at java.lang.Thread.run(Thread.java:818)
                 Caused by: java.io.FileNotFoundException: https://f80a1a79-5d2f-4fe1-8ff3-f78abcad4fb1-bluemix.cloudant.com:443/ocimaoi/_bulk_get
                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
                        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                        at com.cloudant.http.HttpConnection.responseAsInputStream(HttpConnection.java:420)
                        at com.cloudant.mazha.CouchClient.execute(CouchClient.java:176)
                        at com.cloudant.mazha.CouchClient.isBulkSupported(CouchClient.java:749) 
                        at com.cloudant.sync.replication.CouchClientWrapper.isBulkSupported(CouchClientWrapper.java:280) 
                        at com.cloudant.sync.replication.PullStrategy.run(PullStrategy.java:176) 
                        at java.lang.Thread.run(Thread.java:818) 
```
Note: setting the default permissions for all users does not cause this error. Only when I attempt to use specific api key credentials with version 1.1.3 does this occur.

### PR DESCRIPTION
**Pull request by rhyshort**
## What

Correctly generate the URI for the cookie interceptor so it can perform
authentication. 

## How

Remove the last whole path component of the supplied URI, which is the database name that the replication is replicating with.

## Testing

Manual testing against Cloudant.
The Jenkinsfile testing from #411 will automatically run tests that show up this kind of problem.

## Issues

Fixes #415

### CODE REVIEW

File: cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/replication/ReplicatorBuilder.java [hunk 1]
```diff
@@ -70,7 +70,27 @@ private URI addCookieInterceptorIfRequired(URI uri) {
...
+                }
+
+                path = path.substring(0, index);
+
+                URI baseURI;
+
+                try {
+                    baseURI = new URI(uriProtocol, null, uriHost, uriPort, path, null, null);
+                } catch (URISyntaxException e) {
+                    throw new RuntimeException(e);
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/main/java/com/cloudant/sync/replication/ReplicatorBuilder.java]: I don't like this, but as it is already the approach defined here I think it just needs to get covered under #280 for v2 API exceptions.
