### PR TITLE
373 index update tx

### LINKED ISSUE #373: Index updates are not persisted correctly
A bug introduced in version 1.1.0 is preventing index updates from being persisted correctly.

To reproduce:
```java
String indexName = indexManager.ensureIndexed(Collections.singletonList((Object) "myField"), "myIndex");
Map<String, Object> query = new HashMap<String, Object>();
query.put("myField", "myValue");
QueryResult r = im.find(query);
```
Query takes 10 ms.

If I then restart the application and do the query again the query takes 1.3 seconds. I can see that the index database contains no entries.

### PR DESCRIPTION
**Pull request by ricellis**
*What*

Fixed issue persisting index updates.

*How*

When the `IndexUpdater` was refactored to use the a `SQLDatabaseQueue` it was changed to use `submitTransaction` instead of starting and ending the transaction itself, but the `beginTransaction()` call was never removed. This started a nested transaction that was never completed.

* Removed obsolete `beginTransaction()` call.
* Updated `CHANGES.md`.

*Testing*

Added two new tests:

* `indexUpdatesPersistFromCreation()`
* `indexUpdatesPersistExistingIndex()`

*Issues*

Fixes #373

### CODE REVIEW

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java [hunk 1]
```diff
@@ -1041,6 +1041,114 @@ public Void call(SQLDatabase db) throws Exception {
...
+
+            im.updateAllIndexes();
+            exepctedSequence = getIndexSequenceNumber("testIndex");
+            Assert.assertEquals("The expected sequence should be 2 for 2 documents created.", 2,
+                    exepctedSequence);
+        } finally {
+            im.close();
+        }
+
+        // Now get a new IndexManager and queue and update the test fields accordingly
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java]: This comment is wrong

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java [hunk 2]
```diff
@@ -1041,6 +1041,114 @@ public Void call(SQLDatabase db) throws Exception {
...
+            ds.createDocumentFromRevision(rev);
+
+            createIndex("testIndex", Collections.singletonList((Object) "name"));
+            exepctedSequence = getIndexSequenceNumber("testIndex");
+            Assert.assertEquals("The expected sequence should be 1 for 1 document created.", 1,
+                    exepctedSequence);
+        } finally {
+            im.close();
+        }
+        // Now get a new IndexManager and queue and update the test fields accordingly
```
Comment (tomblench) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java]: This comment is wrong

**Comment by tomblench** [comment]
Tests look fine except for a few copy/paste comments.

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java (hunk 1 above)
Comment (ricellis) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java]: Replaced with the hopefully more clear 
`// Get a new IndexManager instance and extract its queue`
in 529262a

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java (hunk 2 above)
Comment (ricellis) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/query/IndexUpdaterTest.java]: Replaced with the hopefully more clear 
`// Get a new IndexManager instance and extract its queue`
in 529262a
