### PR TITLE
527 settings npe

### LINKED ISSUE #527: "IndexCreator: Failed to list indexes" after migration to 2.0.0
I'm trying to migrate app to latest version. In case of fresh installation things work smoothly. But if user already has datastore there is a problem with indexes or datastore. 

*I/SQLDatabaseFactory: Did not create directories for path: /data/user/0/<package name>r/app_data/documents/db.sync directories may already exist
I/SQLDatabaseFactory: Did not create directories for path: /data/user/0/<package name>/app_data/documents/extensions/com.cloudant.sync.query/indexes.sqlite directories may already exist
 E/IndexCreator: Failed to list indexes
                                                                                       java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
                                                                                           at java.util.concurrent.FutureTask.report(FutureTask.java:94)
                                                                                           at java.util.concurrent.FutureTask.get(FutureTask.java:164)
                                                                                           at com.cloudant.sync.internal.documentstore.DatabaseImpl.get(DatabaseImpl.java:1147)
                                                                                           at com.cloudant.sync.internal.query.IndexCreator.ensureIndexed(IndexCreator.java:116)
                                                                                           at com.cloudant.sync.internal.query.IndexCreator.ensureIndexed(IndexCreator.java:60)
                                                                                           at com.cloudant.sync.internal.query.QueryImpl.ensureIndexed(QueryImpl.java:173)
                                                                                           at com.cloudant.sync.internal.query.QueryImpl.createJsonIndex(QueryImpl.java:146)*

### PR DESCRIPTION
**Pull request by ricellis**
*What*

Corrected NPE when trying to read `settings` from a migrated index.

*How*

Added a `null` check before attempting to call `getBytes` for deserialization.

*Testing*

Added test class `Index2MigrationTest` which generates a version 1 index. It uses workarounds similar to those in `Database200MigrationTest` to recreate a v1 index.
Added a new test that migrates the version 1 index to version 2 and then calls `listIndexes` which successfully reproduced the NPE.

*Issues*

Fixes #527

### CODE REVIEW

File: cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/query/Index2MigrationTest.java [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+import org.junit.Test;
+
+import java.util.Arrays;
+import java.util.concurrent.Future;
+
+public class Index2MigrationTest extends AbstractIndexTestBase {
+
+    /**
+     * Version 2 of the index includes an additional index_settings column, which defaults to a null
+     * value. This method pretends we have a
```
Comment (ricellis) [inline cloudant-sync-datastore-core/src/test/java/com/cloudant/sync/internal/query/Index2MigrationTest.java]: Changed it too many times! A complete description in d366d18
